# Chp14. Recurrent Neural Networks

- 발표자 : 송서하
- 발표일 : 2017.9.2(토)
---


In [118]:
import tensorflow as tf
import numpy as np
from sklearn.datasets import fetch_california_housing
import pandas as pd

In [119]:
housing = fetch_california_housing()
data = housing.data
m, n = data.shape
data = np.c_[np.ones([m, 1]), data]
target = housing.target.reshape(-1,1)

In [112]:
tf.reset_default_graph()

X = tf.constant(data, dtype=tf.float32, name="X")
y = tf.constant(target, dtype=tf.float32, name="y")
XT = tf.transpose(X)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y)

with tf.Session() as sess:
    theta_value = theta.eval()
    
print(theta_value)

[[ -3.74651413e+01]
 [  4.35734153e-01]
 [  9.33829229e-03]
 [ -1.06622010e-01]
 [  6.44106984e-01]
 [ -4.25131839e-06]
 [ -3.77322501e-03]
 [ -4.26648885e-01]
 [ -4.40514028e-01]]


In [113]:
tf.reset_default_graph()

n_epochs = 1000
learning_rate = 0.01

X = tf.constant(data, dtype=tf.float32, name="X")
X = tf.nn.l2_normalize(X, 0)
y = tf.constant(target, dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n+1, 1], -1, 1), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(mse)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)

Epoch 0 MSE = 5.65986
Epoch 100 MSE = 5.65365
Epoch 200 MSE = 5.64746
Epoch 300 MSE = 5.64128
Epoch 400 MSE = 5.63511
Epoch 500 MSE = 5.62894
Epoch 600 MSE = 5.62278
Epoch 700 MSE = 5.61664
Epoch 800 MSE = 5.61049
Epoch 900 MSE = 5.60437


In [114]:
tf.reset_default_graph()

A = tf.placeholder(tf.float32, shape=(None, 3))
B = A + 5

with tf.Session() as sess:
    print(B.eval(feed_dict={A: [[1,2,3]]}))
    print(B.eval(feed_dict={A: [[4,5,6],[7,8,9]]}))

[[ 6.  7.  8.]]
[[  9.  10.  11.]
 [ 12.  13.  14.]]


In [115]:
g = tf.Graph()
with g.as_default():
    c = tf.constant(1)
    assert c.graph is g
    with tf.Session() as sess:
        print(c.eval())

1


In [116]:
tf.reset_default_graph()

batch_size = 100    
n_batches = int(np.ceil(m / batch_size))

def fetch_batch(epoch, batch_index, batch_size):
    
    return X_batch, y_batch



In [120]:
print(data)

[[   1.            8.3252       41.         ...,    2.55555556   37.88
  -122.23      ]
 [   1.            8.3014       21.         ...,    2.10984183   37.86
  -122.22      ]
 [   1.            7.2574       52.         ...,    2.80225989   37.85
  -122.24      ]
 ..., 
 [   1.            1.7          17.         ...,    2.3256351    39.43
  -121.22      ]
 [   1.            1.8672       18.         ...,    2.12320917   39.43
  -121.32      ]
 [   1.            2.3886       16.         ...,    2.61698113   39.37
  -121.24      ]]
