# Chp14. Recurrent Neural Networks

- 발표자 : 송서하
- 발표일 : 2017.9.2(토)
---


In [2]:
import tensorflow as tf
import numpy as np
from sklearn.datasets import fetch_california_housing

In [18]:
housing = fetch_california_housing()
data = housing.data
m, n = data.shape
data = np.c_[np.ones([m, 1]), data]
target = housing.target.reshape(-1,1)

In [19]:
X = tf.constant(data, dtype=tf.float32, name="X")
y = tf.constant(target, dtype=tf.float32, name="y")
XT = tf.transpose(X)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y)

with tf.Session() as sess:
    theta_value = theta.eval()
    
print(theta_value)

[[ -3.74651413e+01]
 [  4.35734153e-01]
 [  9.33829229e-03]
 [ -1.06622010e-01]
 [  6.44106984e-01]
 [ -4.25131839e-06]
 [ -3.77322501e-03]
 [ -4.26648885e-01]
 [ -4.40514028e-01]]


In [36]:
n_epochs = 1000
learning_rate = 0.01

X = tf.constant(data, dtype=tf.float32, name="X")
X = tf.nn.l2_normalize(X, 0)
y = tf.constant(target, dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n+1, 1], -1, 1), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(mse)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)

Epoch 0 MSE = 5.59411
Epoch 100 MSE = 5.588
Epoch 200 MSE = 5.58189
Epoch 300 MSE = 5.5758
Epoch 400 MSE = 5.56971
Epoch 500 MSE = 5.56363
Epoch 600 MSE = 5.55756
Epoch 700 MSE = 5.5515
Epoch 800 MSE = 5.54544
Epoch 900 MSE = 5.53939


In [34]:
A = tf.placeholder(tf.float32, shape=(None, 3))
B = A + 5
with tf.Session() as sess:
    B1 = B.eval(feed_dict={A: [[1,2,3]]})
    B2 = B.eval(feed_dict={A: [[4,5,6],[7,8,9]]})    
    print(B1)


[[ 6.  7.  8.]]
[[  9.  10.  11.]
 [ 12.  13.  14.]]
